apiVersion: v1
kind: Service
metadata:
  name: shovel
  labels:
    app.kubernetes.io/name: shovel
    app.kubernetes.io/part-of: sendapp
    app.kubernetes.io/component: indexer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: shovel
