apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shovel-secrets
spec:
  secretStoreRef:
    name: op-sendapp-dev
    kind: ClusterSecretStore
  target:
    name: shovel-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: shovel-dev
        property: DATABASE_URL
    - secretKey: DASHBOARD_ROOT_PASSWORD
      remoteRef:
        key: shovel-dev
        property: DASHBOARD_ROOT_PASSWORD
    - secretKey: BASE_RPC_URL_PRIMARY
      remoteRef:
        key: shovel-dev
        property: BASE_RPC_URL_PRIMARY
    - secretKey: BASE_RPC_URL_BACKUP1
      remoteRef:
        key: shovel-dev
        property: BASE_RPC_URL_BACKUP1
    - secretKey: BASE_RPC_URL_BACKUP2
      remoteRef:
        key: shovel-dev
        property: BASE_RPC_URL_BACKUP2
    - secretKey: BASE_RPC_URL_BACKUP3
      remoteRef:
        key: shovel-dev
        property: BASE_RPC_URL_BACKUP3
    - secretKey: BASE_WS_URL
      remoteRef:
        key: shovel-dev
        property: BASE_WS_URL
    - secretKey: BASE_CHAIN_ID
      remoteRef:
        key: shovel-dev
        property: BASE_CHAIN_ID
    - secretKey: BASE_BLOCK_START
      remoteRef:
        key: shovel-dev
        property: BASE_BLOCK_START
    - secretKey: BASE_NAME
      remoteRef:
        key: shovel-dev
        property: BASE_NAME
