apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shovel-oauth2-proxy
  labels:
    app: oauth2-proxy-shovel
    component: authentication
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - shovel-testnet.send.it
      secretName: shovel-testnet-tls
  rules:
    - host: shovel-testnet.send.it
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy-shovel
                port:
                  number: 4180
