apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shovel
  labels:
    app.kubernetes.io/name: shovel
    app.kubernetes.io/instance: shovel-testnet
    app.kubernetes.io/part-of: sendapp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - shovel-testnet.send.it
      secretName: shovel-testnet-tls
  rules:
    - host: shovel-testnet.send.it
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shovel
                port:
                  name: http
