apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
spec:
  secretStoreRef:
    name: op-shared-oauth
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: google-oauth-monitoring
        property: client_id
    - secretKey: client-secret
      remoteRef:
        key: google-oauth-monitoring
        property: client_secret
    - secretKey: cookie-secret
      remoteRef:
        key: google-oauth-monitoring
        property: cookie_secret
