apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: temporal-workers-mainnet

resources:
  - ../../base
  - externalsecret.yaml
  - ghcr-externalsecret.yaml

patches:
  - target:
      kind: Deployment
      name: temporal-workers
    patch: |-
      - op: add
        path: /metadata/labels/app.kubernetes.io~1instance
        value: temporal-workers-mainnet
      - op: add
        path: /metadata/labels/environment
        value: mainnet
      - op: add
        path: /spec/template/metadata/labels/app.kubernetes.io~1instance
        value: temporal-workers-mainnet
      - op: add
        path: /spec/template/metadata/labels/environment
        value: mainnet
