apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-ghcr
spec:
  secretStoreRef:
    name: op-sendapp-dev
    kind: ClusterSecretStore
  target:
    name: github-ghcr
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: github-ghcr-token
        property: username
    - secretKey: password
      remoteRef:
        key: github-ghcr-token
        property: password
