apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: temporal-worker-secrets
spec:
  secretStoreRef:
    name: op-infrastructure
    kind: ClusterSecretStore
  target:
    name: temporal-worker-secrets
    creationPolicy: Owner
  data:
    - secretKey: BASE_RPC_URL
      remoteRef:
        key: temporal-workers-dev
        property: BASE_RPC_URL
    - secretKey: DEBUG
      remoteRef:
        key: temporal-workers-dev
        property: DEBUG
    - secretKey: ERC7677_BUNDLER_RPC_URL
      remoteRef:
        key: temporal-workers-dev
        property: ERC7677_BUNDLER_RPC_URL
    - secretKey: NEXT_PUBLIC_BASE_CHAIN_ID
      remoteRef:
        key: temporal-workers-dev
        property: NEXT_PUBLIC_BASE_CHAIN_ID
    - secretKey: NEXT_PUBLIC_BASE_RPC_URL
      remoteRef:
        key: temporal-workers-dev
        property: NEXT_PUBLIC_BASE_RPC_URL
    - secretKey: NEXT_PUBLIC_BUNDLER_RPC_URL
      remoteRef:
        key: temporal-workers-dev
        property: NEXT_PUBLIC_BUNDLER_RPC_URL
    - secretKey: NEXT_PUBLIC_SUPABASE_URL
      remoteRef:
        key: temporal-workers-dev
        property: NEXT_PUBLIC_SUPABASE_URL
    - secretKey: NODE_ENV
      remoteRef:
        key: temporal-workers-dev
        property: NODE_ENV
    - secretKey: SUPABASE_DB_URL
      remoteRef:
        key: temporal-workers-dev
        property: SUPABASE_DB_URL
    - secretKey: SUPABASE_JWT_SECRET
      remoteRef:
        key: temporal-workers-dev
        property: SUPABASE_JWT_SECRET
    - secretKey: SUPABASE_SERVICE_ROLE
      remoteRef:
        key: temporal-workers-dev
        property: SUPABASE_SERVICE_ROLE
    - secretKey: TEMPORAL_ADDR
      remoteRef:
        key: temporal-workers-dev
        property: TEMPORAL_ADDR
    - secretKey: TEMPORAL_MTLS_TLS_CERT
      remoteRef:
        key: temporal-workers-dev
        property: TEMPORAL_MTLS_TLS_CERT
    - secretKey: TEMPORAL_MTLS_TLS_KEY
      remoteRef:
        key: temporal-workers-dev
        property: TEMPORAL_MTLS_TLS_KEY
    - secretKey: TEMPORAL_NAMESPACE
      remoteRef:
        key: temporal-workers-dev
        property: TEMPORAL_NAMESPACE
